export const ActionTypes={
    GET_USER:'GET_USER',
    GET_DEPARTS:'GET_DEPARTS',
    GET_APS:'GET_APS',
    SET_CURRENT_USER:'SET_CURRENT_USER',
    GET_CURRENT_USER:'GET_CURRENT_USER',
    DELETE_CURRENT_USER:'DELETE_CURRENT_USER',
    SET_INCOME:'SET_INCOME',
    GET_INCOMES:'GET_INCOMES',
    SET_ASSIGNED_INCOME:'SET_ASSIGNED_INCOME',
    UPDATE_CURRENT_USER:'UPDATE_CURRENT_USER',
};